# application.yml
---
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon.enabled: false
    # spring cloud gateway routes
    gateway:
      discovery:
        locator:
          # spring.cloud.gateway.discovery.locator.enabled abilita la definizione implicita di rotte
          # sulla base dei servizi registrati nel servizio di service discover (default=false)
          # enabled: true
          enabled: false
      routes:
        - id: recensioni_seguite_route
          uri: lb://recensioni-seguite
          predicates:
            - Path=/recensioni-seguite/**
          filters:
            - StripPrefix=1
        - id: recensioni_route
          uri: lb://recensioni
          predicates:
            - Path=/recensioni/**
          filters:
            - StripPrefix=1
        - id: connessioni_route
          uri: lb://connessioni
          predicates:
            - Path=/connessioni/**
          filters:
            - StripPrefix=1

server:
  #  port: ${PORT:${SERVER_PORT:0}}
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: info,health,gateway,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.gateway: INFO
