# application.yml
---
spring:
  application:
    name: recensioni



  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://recensioni-db:5432/recensionidb
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    open-in-view: false
    show-sql: false

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 0

server:

  # Se necessario, puoi fissare una porta (es. 8080)
  port: 8080
  # Per Swagger, se dietro a un API Gateway
  forward-headers-strategy: framework

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
      hibernate:
        SQL: INFO
    asw:
      recensioni: DEBUG

# MESSAGING
asw:
  kafka:
    producer:
      name: Producer2
    channel:
      out: recensioni
    # groupid: simple-producer
